In [1]:
import numpy as np
np.random.seed(42)

tokens = ["What", "are", "the", "symptoms", "of", "diabetes", "?"]
seq_len = len(tokens)   
d_model  = 8          
d_k      = 4           

print("=" * 60)
print("INPUT SENTENCE: 'What are the symptoms of diabetes?'")
print(f"Tokens : {tokens}")
print(f"seq_len={seq_len}, d_model={d_model}, d_k={d_k}")
print("=" * 60)

X = np.random.randn(seq_len, d_model)  

W_Q = np.random.randn(d_model, d_k)    
W_K = np.random.randn(d_model, d_k)    
W_V = np.random.randn(d_model, d_k)    

Q = X @ W_Q     
K = X @ W_K     
V = X @ W_V     

print("\n── Query Matrix Q (7×4) ──")
print(np.round(Q, 3))

print("\n── Key Matrix K (7×4) ──")
print(np.round(K, 3))

scores_raw = Q @ K.T                  
scores_scaled = scores_raw / np.sqrt(d_k)   

print("\n── Raw Attention Scores  QKᵀ  (7×7) ──")
print(np.round(scores_raw, 3))

print("\n── Scaled Scores  QKᵀ/√d_k  (7×7) ──")
print(np.round(scores_scaled, 3))

def softmax(x, axis=-1):
    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return e_x / e_x.sum(axis=axis, keepdims=True)

attention_weights = softmax(scores_scaled, axis=-1)   

print("\n── Attention Weights after Softmax (7×7) ──")
print(np.round(attention_weights, 4))

output = attention_weights @ V    

print("\n── Self-Attention Output  Z  (7×4) ──")
print(np.round(output, 4))

print("\n── Strongest Attention per Token ──")
print(f"{'Token':<12} {'Attends Most To':<15} {'Weight':>8}")
print("-" * 38)
for i, token in enumerate(tokens):
    j = np.argmax(attention_weights[i])
    print(f"{token:<12} {tokens[j]:<15} {attention_weights[i][j]:.4f}")

INPUT SENTENCE: 'What are the symptoms of diabetes?'
Tokens : ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']
seq_len=7, d_model=8, d_k=4

── Query Matrix Q (7×4) ──
[[-0.253 -0.35   4.45   3.349]
 [ 0.247  0.333 -4.764  2.422]
 [ 0.516  3.034 -6.193 -3.297]
 [-1.765 -3.652  2.269 -0.234]
 [ 0.7    2.443 -1.844  5.02 ]
 [-1.668 -3.016  4.049  0.738]
 [-0.221 -0.432  6.108  0.177]]

── Key Matrix K (7×4) ──
[[-2.084e+00  2.745e+00  1.650e-01  3.280e-01]
 [-2.260e-01 -3.695e+00  3.716e+00 -1.616e+00]
 [ 1.805e+00  2.175e+00  1.814e+00 -8.840e-01]
 [-7.410e-01 -4.642e+00  1.428e+00  3.930e-01]
 [ 2.096e+00 -2.204e+00  5.471e+00  2.157e+00]
 [-1.310e-01 -2.495e+00 -4.000e-03  1.150e+00]
 [ 1.993e+00  2.133e+00 -7.260e-01  4.023e+00]]

── Raw Attention Scores  QKᵀ  (7×7) ──
[[  1.4    12.469   3.896   9.482  31.808   4.74    8.992]
 [  0.41  -22.905  -9.614  -7.582 -21.053   1.94   14.408]
 [  5.151 -29.01   -0.792 -24.609 -46.598 -11.406  -1.268]
 [ -6.05   22.705  -6.805  21.411